name: Trigger auto deployment for sp-cdci-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/sp-cdci-test-AutoDeployTrigger-7753bd1f-3919-4ae8-92c6-db8115fcc0cc.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPCDCITEST_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: oidcredistry5.azurecr.io
          registryUsername: ${{ secrets.SPCDCITEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPCDCITEST_REGISTRY_PASSWORD }}
          containerAppName: sp-cdci-test
          resourceGroup: Testing
          imageToBuild: oidcredistry5.azurecr.io/sp-cdci-test:${{ github.sha }}
          dockerfilePath: Dockerfile

     

